name: Run test after push

on: push 

jobs: 
  name: runing tests after push
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        # uses используется когда мы как шаг используем готовый action от github
        uses: actions/checkout@v3
        #  with параметр в котором мы описываем что action будет работать с определнными параметрами 
        # with:
      - name: Install dependecies
        run: npm ci
      - name: Runing tests
        run: npm cypress:test