name: Running ledgers api tests

on:
  push:
  workflow_dispatch:

jobs:
  running-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: newman run .postman/mc.postman_collection.json -e .postman/pre_mc.postman_environment.json
