name: Running ledgers api tests

on:
  push:
  workflow_dispatch:

jobs:
  running-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: sashalemeshonok/my-cypress-project
          path: ./postman

      - name: Install Newman
        run: npm install -g newman

      - name: Run Postman Collection
        run: newman run ledger_collection.json -e pre.ledger_env.json
