name: Runing tests in other jobs after push

on:
  push:
    branche: [main]

jobs:
  working-with-kufar:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Cashe dependecies
        uses: actions/cashe@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependecies
        run: npm ci
      - name: Runing tests
        run: npm run cypress:test:first
        continue-on-error: true
      - name: Runing tests
        run: npm run cypress:test:second
      - name: Get rep object
        run: echo "${{}}"
