name: Runing tests in other jobs after push

on: push

jobs:
  working-with-kufar:
    runs-on: ubuntu-latest
    needs: working-with-auto-kufar
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm ci
      - name: Runing tests
        run: npm run cypress:test:first
        continue-on-error: true
      - name: Runing tests
        run: npm run cypress:test:second
